version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: judge_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: judge_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: judge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
